### ISSUE TITLE
1.2.5失效了

### ISSUE THREAD

**Issue by GMYXDS** [sfc9982/typoraActivator#1]
typora 版本 1.2.5
```shell
2022-05-30 08:13:14.327 | INFO     | __main__:extractWdec:66 - extract asar file: D:/Program Files/Typora/resources/app.asar
2022-05-30 08:13:14.338 | SUCCESS  | __main__:extractWdec:69 - extract ended.
2022-05-30 08:13:14.340 | INFO     | __main__:extractWdec:71 - read Directory: D:/Program Files/Typora/resources/outfile\temp
2022-05-30 08:13:14.341 | WARNING  | __main__:_mkdir:40 - May FolderExists: D:/Program Files/Typora/resources/outfile\dec_app
2022-05-30 08:13:14.341 | INFO     | __main__:extractWdec:76 - set Directory: D:/Program Files/Typora/resources/outfile\dec_app
2022-05-30 08:13:14.343 | INFO     | __main__:extractWdec:83 - open file: atom.js
Traceback (most recent call last):
  File "./typora.py", line 170, in <module>
    main()
  File "./typora.py", line 165, in main
    args.mode(args.asarPath, args.dirPath, args.format)
  File "./typora.py", line 86, in extractWdec
    scode = decScript(scode, prettify)
  File "./typora.py", line 51, in decScript
    code = unpad(ins.decrypt(cipherText), 16, 'pkcs7')
  File "C:\Users\ee\AppData\Local\Programs\Python\Python38\lib\site-packages\Crypto\Util\Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
```

**Comment by sfc9982** [comment]
@GMYXDS 使用[Yoshino-s/ElectronInjector](https://github.com/Yoshino-s/ElectronInjector)
