### ISSUE TITLE
Not working for version 1.9.5

### ISSUE THREAD

**Issue by bolavefasfas** [sfc9982/typoraActivator#4]
```
python typora.py "C:/Users/USER/Downloads/typora/app.asar" "C:/Users/USER/Downloads/"
2024-08-17 14:11:40.992 | INFO     | __main__:extractWdec:66 - extract asar file: C:/Users/USER/Downloads/typora/app.asar
Couldn't copy file .\main.node, no extracted directory
2024-08-17 14:11:40.998 | SUCCESS  | __main__:extractWdec:69 - extract ended.
2024-08-17 14:11:40.999 | INFO     | __main__:extractWdec:71 - read Directory: C:/Users/USER/Downloads/temp
2024-08-17 14:11:41.000 | WARNING  | __main__:_mkdir:40 - May FolderExists: C:/Users/USER/Downloads\dec_app
2024-08-17 14:11:41.001 | INFO     | __main__:extractWdec:76 - set Directory: C:/Users/USER/Downloads\dec_app
2024-08-17 14:11:41.020 | INFO     | __main__:extractWdec:83 - open file: atom.js
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\Compressed\typoraActivator-main\typoraActivator-main\typora.py", line 170, in <module>
    main()
  File "C:\Users\USER\Downloads\Compressed\typoraActivator-main\typoraActivator-main\typora.py", line 165, in main
    args.mode(args.asarPath, args.dirPath, args.format)
  File "C:\Users\USER\Downloads\Compressed\typoraActivator-main\typoraActivator-main\typora.py", line 86, in extractWdec
    scode = decScript(scode, prettify)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Downloads\Compressed\typoraActivator-main\typoraActivator-main\typora.py", line 51, in decScript
    code = unpad(ins.decrypt(cipherText), 16, 'pkcs7')
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode
```

**Comment by sfc9982** [comment]
not working for latest versions, please use other methods, thanks.

**Comment by bolavefasfas** [comment]
> not working for latest versions, please use other methods, thanks.

Do you know any repo that will work for latest version ?

**Comment by sfc9982** [comment]
You can google out the answer and post it here.

**Comment by bolavefasfas** [comment]
> You can google out the answer and post it here.

Did ot find any working.
Searched all
